services:
  testrunner:
    image: $DEV_IMAGE_TAG
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        OTP_VERSION: $OTP_VERSION
        THRIFT_VERSION: $THRIFT_VERSION
    volumes:
      - .:$PWD
    hostname: $SERVICE_NAME
    working_dir: $PWD
    depends_on:
      dmt:
        condition: service_healthy
      shumway:
        condition: service_started
    ports:
      - "8022:8022"
    command: /sbin/init

  dmt:
    image: ghcr.io/valitydev/dominant-v2:sha-bfed984
    command: /opt/dmt/bin/dmt foreground
    healthcheck:
      test: "/opt/dmt/bin/dmt ping"
      interval: 5s
      timeout: 3s
      retries: 12
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./test/dmt/sys.config:/opt/dmt/releases/0.1/sys.config

  shumway:
    image: ghcr.io/valitydev/shumway:sha-658587c
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - java
      - -Xmx512m
      - -jar
      - /opt/shumway/shumway.jar
      - --spring.datasource.url=jdbc:postgresql://db:5432/shumway
      - --spring.datasource.username=shumway
      - --spring.datasource.password=postgres
      - --management.endpoint.metrics.enabled=false
      - --management.endpoint.prometheus.enabled=false
    healthcheck:
      disable: true

  db:
    image: postgres:15-bookworm
    command: -c 'max_connections=1000'
    environment:
      POSTGRES_MULTIPLE_DATABASES: "dmt,shumway"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./test/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hellgate"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
