services:

  testrunner:
    image: $DEV_IMAGE_TAG
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        OTP_VERSION: $OTP_VERSION
        THRIFT_VERSION: $THRIFT_VERSION
    volumes:
      - .:$PWD
    hostname: $SERVICE_NAME
    working_dir: $PWD
    depends_on:
      machinegun:
        condition: service_healthy
      dominant:
        condition: service_healthy
      shumway:
        condition: service_healthy
    ports:
      - "8022:8022"
    command: /sbin/init

  dominant:
    image: ghcr.io/valitydev/dominant:sha-486d2ef
    depends_on:
      - machinegun
    ports:
      - "8022"
    command: /opt/dominant/bin/dominant foreground
    healthcheck:
      test: "/opt/dominant/bin/dominant ping"
      interval: 5s
      timeout: 1s
      retries: 20

  machinegun:
    image: ghcr.io/valitydev/machinegun:sha-7f0a21a
    ports:
      - "8022"
    command: /opt/machinegun/bin/machinegun foreground
    volumes:
      - ./test/machinegun/config.yaml:/opt/machinegun/etc/config.yaml
      - ./test/machinegun/cookie:/opt/machinegun/etc/cookie
    healthcheck:
      test: "/opt/machinegun/bin/machinegun ping"
      interval: 5s
      timeout: 1s
      retries: 20

  shumway:
    image: ghcr.io/valitydev/shumway:sha-658587c
    restart: unless-stopped
    depends_on:
      - shumway-db
    ports:
      - "8022"
      - "8023"
    entrypoint:
      - java
      - -Xmx512m
      - -jar
      - /opt/shumway/shumway.jar
      - --spring.datasource.url=jdbc:postgresql://shumway-db:5432/shumway
      - --spring.datasource.username=postgres
      - --spring.datasource.password=postgres
      - --management.endpoint.metrics.enabled=false
      - --management.endpoint.prometheus.enabled=false
      - --management.endpoint.health.show-details=always
      - --management.endpoint.health.probes.enabled=true
      - --management.server.port=8023
      - --management.endpoints.web.exposure.include=health,info
    healthcheck:
      test: curl http://shumway:8023/actuator/health/liveness
      interval: 5s
      timeout: 1s
      retries: 20

  shumway-db:
    image: docker.io/library/postgres:13.10
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=shumway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
