services:

  testrunner:
    image: $DEV_IMAGE_TAG
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        OTP_VERSION: $OTP_VERSION
        THRIFT_VERSION: $THRIFT_VERSION
    volumes:
      - .:$PWD
    hostname: $SERVICE_NAME
    working_dir: $PWD
    depends_on:
      machinegun:
        condition: service_started
      dominant:
        condition: service_started
      shumway:
        condition: service_healthy
    ports:
      - "8022:8022"
    command: /sbin/init

  dominant:
    image: ghcr.io/valitydev/dominant:sha-8bd7828
    depends_on:
      - machinegun
    ports:
      - "8022"
    command: /opt/dominant/bin/dominant foreground

  machinegun:
    image: docker.io/rbkmoney/machinegun:c05a8c18cd4f7966d70b6ad84cac9429cdfe37ae
    ports:
      - "8022"
    command: /opt/machinegun/bin/machinegun foreground
    volumes:
      - ./test/machinegun/config.yaml:/opt/machinegun/etc/config.yaml
      - ./test/machinegun/cookie:/opt/machinegun/etc/cookie

  shumway:
    image: docker.io/rbkmoney/shumway:44eb989065b27be619acd16b12ebdb2288b46c36
    restart: unless-stopped
    depends_on:
      - shumway-db
    ports:
      - "8022"
    entrypoint:
      - java
      - -Xmx512m
      - -jar
      - /opt/shumway/shumway.jar
      - --spring.datasource.url=jdbc:postgresql://shumway-db:5432/shumway
      - --spring.datasource.username=postgres
      - --spring.datasource.password=postgres
      - --management.metrics.export.statsd.enabled=false
    healthcheck:
      test: curl http://localhost:8022/
      interval: 5s
      timeout: 1s
      retries: 20

  shumway-db:
    image: docker.io/library/postgres:9.6
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=shumway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
