name: Build Docker image
on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

env:
  REGISTRY: ghcr.io

jobs:
  build:
#    if: ${{ !(matrix.only-master && (github.ref != 'refs/heads/master')) }}
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/arm64
            arch: arm64
            only-master: true
          - platform: linux/amd64
            arch: amd64
            only-master: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construct tags / labels for an image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=sha

      # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Update environment variables
        run: grep -v '^#' .env >> $GITHUB_ENV

      - name: Set up QEMU
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-cache-${{ matrix.arch }}
          restore-keys: |
            buildx-cache-

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
#          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platform }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          build-args: |
            OTP_VERSION=${{ env.OTP_VERSION }}
            THRIFT_VERSION=${{ env.THRIFT_VERSION }}
            SERVICE_NAME=${{ env.SERVICE_NAME }}
